import JSZip from 'jszip';
import { LiveArtifact, User } from '../types';

export interface ZipExportOptions {
  artifact: LiveArtifact;
  currentUser?: User | null;
  onRequireUpgrade?: () => void;
}

export interface ZipExportResult {
  success: boolean;
  message?: string;
  blob?: Blob;
  filename?: string;
}

// Client-side rate limiting tracker (Anti-Abuse / Anti-Bomb)
const clientZipRateLimit = {
  lastDownloads: [] as number[],
  MAX_PER_MINUTE: 5
};

/**
 * Generate a complete, deployable multi-file project ZIP archive.
 * Strictly gated: Only Premium and Owner roles can export ZIP archives.
 */
export async function exportProjectZip({
  artifact,
  currentUser,
  onRequireUpgrade
}: ZipExportOptions): Promise<ZipExportResult> {
  const isPremiumOrOwner = currentUser?.role === 'premium' || 
                           currentUser?.role === 'owner' || 
                           currentUser?.role === 'developer';

  // 1. Gating Check
  if (!isPremiumOrOwner) {
    if (onRequireUpgrade) {
      onRequireUpgrade();
    }
    return {
      success: false,
      message: 'ZIP export is a Premium feature. Please upgrade to download complete project ZIP archives.'
    };
  }

  // 2. Client-side Rate Limit Check
  const now = Date.now();
  clientZipRateLimit.lastDownloads = clientZipRateLimit.lastDownloads.filter(t => now - t < 60000);
  if (clientZipRateLimit.lastDownloads.length >= clientZipRateLimit.MAX_PER_MINUTE) {
    return {
      success: false,
      message: 'Rate limit: You can download up to 5 ZIP archives per minute. Please wait a few seconds.'
    };
  }

  // 3. Anti-Zip-Bomb Safety Check
  const codeLength = artifact.code ? artifact.code.length : 0;
  if (codeLength > 5 * 1024 * 1024) { // 5MB source code limit
    return {
      success: false,
      message: 'Code payload exceeds safety limit (max 5MB).'
    };
  }

  try {
    // Attempt server-side export first for authenticated rate-limited generation
    if (currentUser?.id) {
      try {
        const response = await fetch('/api/export/zip', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'x-user-id': currentUser.id
          },
          body: JSON.stringify({
            title: artifact.title,
            type: artifact.type,
            code: artifact.code
          })
        });

        if (response.ok) {
          const blob = await response.blob();
          clientZipRateLimit.lastDownloads.push(now);
          const sanitizedTitle = artifact.title.toLowerCase().replace(/[^a-z0-9_-]/g, '-') || 'beldi-ai-project';
          const filename = `${sanitizedTitle}.zip`;
          
          triggerBlobDownload(blob, filename);
          return { success: true, blob, filename };
        } else if (response.status === 403) {
          const errData = await response.json().catch(() => ({}));
          if (onRequireUpgrade) onRequireUpgrade();
          return {
            success: false,
            message: errData.error || 'ZIP export requires a Premium subscription.'
          };
        } else if (response.status === 429) {
          const errData = await response.json().catch(() => ({}));
          return {
            success: false,
            message: errData.error || 'Download rate limit exceeded. Please wait a moment.'
          };
        }
      } catch (srvErr) {
        console.warn('Server zip endpoint unreachable, generating client-side bundle...', srvErr);
      }
    }

    // Fallback: Safe Client-Side Generation via JSZip
    const zip = new JSZip();
    const sanitizedTitle = artifact.title.replace(/[^a-zA-Z0-9 _-]/g, '').trim() || 'Beldi AI Project';
    const folderSlug = sanitizedTitle.toLowerCase().replace(/\s+/g, '-');

    // 1. Process Code and create clean index.html
    let fullHtml = artifact.code;
    if (!fullHtml.includes('<!DOCTYPE html>')) {
      fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${sanitizedTitle}</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <link rel="stylesheet" href="style.css">
</head>
<body class="bg-black text-white min-h-screen">
  ${artifact.code}
  <script src="app.js"></script>
</body>
</html>`;
    }

    // Add files to ZIP
    zip.file('index.html', fullHtml);

    // CSS file
    zip.file('style.css', `/* Built with Beldi AI by Build X */
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');

body {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}
`);

    // JS file
    zip.file('app.js', `// Interactive logic generated by Beldi AI
console.log('Beldi AI Applet "${sanitizedTitle}" initialized successfully.');
`);

    // README.md documentation
    zip.file('README.md', `# ${sanitizedTitle}

> Generated by **Beldi AI** (Crafted by **Build X** &bull; [@build_x_official](https://instagram.com/build_x_official))

## 🚀 Overview
- **Project Name:** ${sanitizedTitle}
- **Artifact Type:** ${artifact.type.toUpperCase()}
- **Generated On:** ${new Date().toUTCString()}

## 🛠️ Quick Start & Running Locally
1. Unzip this package to any folder.
2. Open \`index.html\` directly in any web browser (Chrome, Safari, Firefox, Edge, Brave).
3. Alternatively, launch a local web server:
   \`\`\`bash
   # Using Python
   python3 -m http.server 8000
   
   # Using Node.js npx
   npx serve .
   \`\`\`
4. Navigate to \`http://localhost:8000\` or \`http://localhost:3000\`.

## 📦 Deployment
You can deploy this site in seconds to:
- **Vercel**: \`npx vercel\`
- **Netlify**: Drag and drop the unzipped folder into [Netlify Drop](https://app.netlify.com/drop)
- **GitHub Pages**: Push this repository to GitHub and enable Pages in Settings.

---
*Beldi AI &copy; 2026 Build X. All rights reserved.*
`);

    // metadata.json
    zip.file('metadata.json', JSON.stringify({
      name: sanitizedTitle,
      type: artifact.type,
      author: currentUser?.name || 'Beldi AI User',
      generator: 'Beldi AI v3.1 (Build X)',
      createdAt: new Date().toISOString(),
      framework: 'HTML5 + Tailwind CSS'
    }, null, 2));

    // Generate zip blob with DEFLATE compression (safely capped)
    const contentBlob = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 }
    });

    clientZipRateLimit.lastDownloads.push(now);
    const filename = `${folderSlug}.zip`;
    triggerBlobDownload(contentBlob, filename);

    return {
      success: true,
      blob: contentBlob,
      filename
    };

  } catch (error: any) {
    console.error('ZIP generation error:', error);
    return {
      success: false,
      message: error.message || 'Failed to construct ZIP package.'
    };
  }
}

function triggerBlobDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
